# Generated by Django 4.2.7 on 2023-12-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='budget_id',
            field=models.CharField(blank=True, help_text='YNAB Budget ID', max_length=100, null=True),
        ),
    ]
