# Generated by Django 4.2.7 on 2023-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_financialsettings_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='budget_name',
            field=models.CharField(blank=True, help_text='YNAB Budget Name', max_length=255, null=True),
        ),
    ]
