# Generated by Django 4.2.7 on 2023-12-20 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_financialsettings_budget_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.CharField(blank=True, help_text='YNAB Budget ID', max_length=100, null=True)),
                ('budget_name', models.CharField(blank=True, help_text='YNAB Budget Name', max_length=255, null=True)),
                ('min_account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('budget_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_settings', to='app.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.home')),
            ],
        ),
        migrations.RenameModel(
            old_name='Salary',
            new_name='UserSalary',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='UserSchedule',
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='financialsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='FinancialInfo',
        ),
        migrations.DeleteModel(
            name='FinancialSettings',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
